// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGxzCgcK23Uzbj9SSPCGYbiWfzVGNwR-c',
    appId: '1:683952482668:web:3c818b47cc26c1c294ab49',
    messagingSenderId: '683952482668',
    projectId: 'w4-sit22-26',
    authDomain: 'w4-sit22-26.firebaseapp.com',
    storageBucket: 'w4-sit22-26.firebasestorage.app',
    measurementId: 'G-S18BSH1M5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hwi442v9S2Mic5Zupw80MoDHa5eRos8',
    appId: '1:683952482668:android:949bed83e7b0a81594ab49',
    messagingSenderId: '683952482668',
    projectId: 'w4-sit22-26',
    storageBucket: 'w4-sit22-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTo5AwMZ_ipAl6G0iA8exQiE82yR38fR4',
    appId: '1:683952482668:ios:47e5c2b3dd77d7f194ab49',
    messagingSenderId: '683952482668',
    projectId: 'w4-sit22-26',
    storageBucket: 'w4-sit22-26.firebasestorage.app',
    iosBundleId: 'com.example.w4',
  );
}
